PORTAL-2903: Add doc for access rework on ER/Flex/Support
akeneo/portal-helpcenter pull request #40
Opened 2020-12-24 14:07 UTC by vilain-corentin

2020-12-28 11:26 UTC, Nuscly reviewed
Need to check *all* existing pages also for other changes, as an example, the activation is not needed anymore here https://help.akeneo.com/portal/articles/get-akeneo-pim-enterprise-archive.html#add-developers-to-the-project-console

2020-12-28 11:26 UTC, Nuscly commented on content/md/cloud/2-access-flexibility-server.md
> +The new contact will receive an email to update his password, and an email indicating that he has access to the flexibility instance.
```suggestion
The new contact will receive an email to define his password, and an email indicating that he has access to the flexibility instance.
```

2020-12-28 11:26 UTC, Nuscly commented on content/md/enterprise-repository/1-get-enterprise-edition-archive.md
> +The new contact will receive an email to update his password and an email indicating that he has access to the enterprise repository.
```suggestion
The new contact will receive an email to define his password and an email indicating that he has access to the enterprise repository.
```

2020-12-28 11:26 UTC, Nuscly commented on content/md/support/manage-support-access.md
> +The new contact will receive an email to update his password and an email indicating that he has access to the support.
```suggestion
The new contact will receive an email to define his Portal password
```
Both info should be merged, as the second one is talking about the second email.

2020-12-30 11:15 UTC, vilain-corentin commented
> Need to check _all_ existing pages also for other changes, as an example, the activation is not needed anymore here https://help.akeneo.com/portal/articles/get-akeneo-pim-enterprise-archive.html#add-developers-to-the-project-console

I reread the whole doc and the rest looks good.

2021-01-04 17:12 UTC, Nuscly commented
Page articles/connect-to-your-portal.html is not needed anymore

2021-01-04 17:16 UTC, Nuscly commented on content/md/cloud/2-access-flexibility-server.md
> +::: info
"Info" should be used to give complementary information, and not the main content of the section.

2021-01-05 07:56 UTC, Nuscly requested changes

2021-01-05 07:56 UTC, Nuscly commented on content/md/support/manage-support-access.md
> +**Add access to an existing contact from another company:**
```suggestion
**Add access to an existing contact from another company**
```

2021-01-05 07:56 UTC, Nuscly commented on content/md/support/manage-support-access.md
> +**Add access to a new contact:**
```suggestion
**Add access to a new contact**
```

2021-01-05 07:56 UTC, Nuscly commented on content/md/support/manage-support-access.md
> +::: info
remove info block

2021-01-05 07:56 UTC, Nuscly commented on content/md/support/manage-support-access.md
> +::: info
Can you remove this info block?

2021-01-05 07:56 UTC, Nuscly commented on content/md/support/manage-support-access.md
> +The contact created at the same time as the access will automatically have the console users group.
```suggestion
```

2021-01-05 07:56 UTC, Nuscly commented on content/md/enterprise-repository/1-get-enterprise-edition-archive.md
> +The contact created at the same time as the access will automatically have the console users group.
```suggestion
```
This explicit on the display.

2021-01-05 07:56 UTC, Nuscly commented on content/md/support/manage-support-access.md
> +**Add access to an existing contact of your company:**
Can you put those actions as a secondary level? They will appear in the left menu, and it will be consistent with other access, as defined above ^^.

2021-01-05 07:56 UTC, Nuscly commented on content/md/support/manage-support-access.md
* The documentation does not contain the reset password link. Can you add it?

2021-01-05 07:58 UTC, Nuscly commented
I also saw that there are some images that are not displayed, like at the end of https://help.akeneo.com/portal/articles/get-akeneo-pim-enterprise-archive.html

2021-01-05 09:55 UTC, vilain-corentin commented
> I also saw that there are some images that are not displayed, like at the end of https://help.akeneo.com/portal/articles/get-akeneo-pim-enterprise-archive.html

Fix done

2021-01-05 09:57 UTC, vilain-corentin commented
> Page articles/connect-to-your-portal.html is not needed anymore, as this is the same URL used for all the users.

Removed

2021-01-05 11:28 UTC, Nuscly commented
Can you replace the occurrence " of your Portal." by "on the Akeno Portal" or something similar, as in the context there is no anymore of specific portal?

2021-01-06 12:46 UTC, Robyn88 commented on content/md/cloud/2-access-flexibility-server.md
> +1. Click on the `Add contact key` button to validate the creation.
instead of validate maybe we use: to approve the key

2021-01-06 12:46 UTC, Robyn88 commented on content/md/cloud/2-access-flexibility-server.md
> +The external contact will be visible from the contacts of your company and will be removed from your company if it is no longer linked to your company. For example, if you delete its access.
if they are no longer linked to your company. For example, if you delete their access.

2021-01-06 12:47 UTC, Robyn88 commented on content/md/cloud/2-access-flexibility-server.md
> +1. In the case of a company contact, you can give him different groups.
give them different permissions

2021-01-06 12:47 UTC, Robyn88 commented on content/md/cloud/2-access-flexibility-server.md
> +The new contact will receive an email to define his password, and an email indicating that he has access to the flexibility instance.
to define their password, and an email indicating that they have access....

2021-01-06 12:48 UTC, Robyn88 commented on content/md/enterprise-repository/1-get-enterprise-edition-archive.md
> +The **project console** is the place in the [Akeneo Portal](https://portal.akeneo.com) where you can manage the accesses to your project such as the Enterprise Repository and get the bootstrap archiv
where you can manage access

2021-01-06 12:50 UTC, Robyn88 commented on content/md/enterprise-repository/1-get-enterprise-edition-archive.md
> +The external contact will be visible from the contacts of your company and will be removed from your company if it is no longer linked to your company. For example, if you delete its access.
The external contact will be visible within the contacts of your company and will be removed from your company if they are longer linked to your company. For example, if you delete their access.

2021-01-06 12:50 UTC, Robyn88 commented on content/md/enterprise-repository/1-get-enterprise-edition-archive.md
> +1. In the case of a company contact, you can give him different groups.
you can assign them different groups

2021-01-06 12:52 UTC, Robyn88 commented on content/md/support/manage-support-access.md
> +1. In the case of a company contact, you can give him different groups.
you can assign them different groups

2021-01-06 12:53 UTC, Robyn88 commented on content/md/support/manage-support-access.md
> +Once your access created in the Akeneo Portal, if you have access to the `JIRA SDS Helpdesk` for the first time, you received an email to reset your `JIRA password`.
Once you have access to the Akeneo portal, you will be able to connector to the JIRA SDS helpdesk for the first time, you will receive an email to reset your password.

2021-01-06 12:53 UTC, Robyn88 commented on content/md/support/manage-support-access.md
> +The contact will receive an email to change his password on the helpdesk.
to change their password on the helpdesk

2021-01-08 09:56 UTC, manolo317 approved these changes

2021-01-12 07:44 UTC, Nuscly approved these changes

2021-01-12 15:26 UTC, merged